// Action Types
export const FETCH_TATTOOS_REQUEST = 'FETCH_TATTOOS_REQUEST';
export const FETCH_TATTOOS_SUCCESS = 'FETCH_TATTOOS_SUCCESS';
export const FETCH_TATTOOS_FAILURE = 'FETCH_TATTOOS_FAILURE';