// Home Banner
export const FETCH_BANNER_REQUEST = 'FETCH_BANNER_REQUEST';
export const FETCH_BANNNER_SUCCESS = 'FETCH_BANNNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';

// Home Slider
export const FETCH_BANNER_SLIDER_REQUEST = 'FETCH_BANNER_SLIDER_REQUEST';
export const FETCH_BANNNER_SLIDER_SUCCESS = 'FETCH_BANNNER_SLIDER_SUCCESS';
export const FETCH_BANNER_SLIDER_FAILURE = 'FETCH_BANNER_SLIDER_FAILURE';

// Home slider gallery
export const FETCH_GALLERY_SLIDER_REQUEST = 'FETCH_GALLERY_SLIDER_REQUEST';
export const FETCH_GALLERY_SLIDER_SUCCESS = 'FETCH_GALLERY_SLIDER_SUCCESS';
export const FETCH_GALLERY_SLIDER_FAILURE = 'FETCH_GALLERY_SLIDER_FAILURE';

