// actionTypes.js
export const CREATE_TATTOO_REQUEST = 'CREATE_TATTOO_REQUEST';
export const CREATE_TATTOO_SUCCESS = 'CREATE_TATTOO_SUCCESS';
export const CREATE_TATTOO_FAILURE = 'CREATE_TATTOO_FAILURE';
