// actionTypes.js
export const FETCH_TATTOO_DETAILS_REQUEST = 'FETCH_TATTOO_DETAILS_REQUEST';
export const FETCH_TATTOO_DETAILS_SUCCESS = 'FETCH_TATTOO_DETAILS_SUCCESS';
export const FETCH_TATTOO_DETAILS_FAILURE = 'FETCH_TATTOO_DETAILS_FAILURE';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';