export const ADD_PLACEMENT_REQUEST = 'ADD_PLACEMENT_REQUEST';
export const ADD_PLACEMENT_SUCCESS = 'ADD_PLACEMENT_SUCCESS';
export const ADD_PLACEMENT_FAILURE = 'ADD_PLACEMENT_FAILURE';
export const FETCH_PLACEMENT_REQUEST = 'FETCH_PLACEMENT_REQUEST';
export const FETCH_PLACEMENT_SUCCESS = 'FETCH_PLACEMENT_SUCCESS';
export const FETCH_PLACEMENT_FAILURE = 'FETCH_PLACEMENT_FAILURE';
export const DELETE_PLACEMENT_FAILURE = 'DELETE_PLACEMENT_FAILURE';
export const DELETE_PLACEMENT_SUCCESS = 'DELETE_PLACEMENT_SUCCESS';